// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"database/sql"
)

type AccountTransaction struct {
	MessageID   string         `json:"message_id"`
	UserID      string         `json:"user_id"`
	CreditCents int32          `json:"credit_cents"`
	DebitCents  int32          `json:"debit_cents"`
	Currency    sql.NullString `json:"currency"`
	Created     sql.NullTime   `json:"created"`
}
