// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"context"
)

type Querier interface {
	GetAccountBalance(ctx context.Context, userID string) (int32, error)
	GetTransactions(ctx context.Context, userID string) ([]AccountTransaction, error)
	InsertCreditTransaction(ctx context.Context, arg InsertCreditTransactionParams) (AccountTransaction, error)
	InsertDebitTransaction(ctx context.Context, arg InsertDebitTransactionParams) (AccountTransaction, error)
}

var _ Querier = (*Queries)(nil)
